<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Matchup Analysis</title>
</head>
<body>
	<a href="index.jsp"> Go Back</a>
	<form action ="analyze">
	Choose a home team:
	<select id="homeTeam" name="homeTeam">
		<option value="Abilene Christian">Abilene Christian</option>
		<option value="Air Force">Air Force</option>
		<option value="Akron">Akron</option>
		<option value="Alabama">Alabama</option>
		<option value="Alabama A&M">Alabama A&M</option>
		<option value="Alabama St.">Alabama St.</option>
		<option value="Albany">Albany</option>
		<option value="Alcorn St.">Alcorn St.</option>
		<option value="American">American</option>
		<option value="Appalachian St.">Appalachian St.</option>
		<option value="Arizona">Arizona</option>
		<option value="Arizona St.">Arizona St.</option>
		<option value="Arkansas">Arkansas</option>
		<option value="Arkansas Pine Bluff">Arkansas Pine Bluff</option>
		<option value="Arkansas St.">Arkansas St.</option>
		<option value="Army">Army</option>
		<option value="Auburn">Auburn</option>
		<option value="Austin Peay">Austin Peay</option>
		<option value="BYU">BYU</option>
		<option value="Ball St.">Ball St.</option>
		<option value="Baylor">Baylor</option>
		<option value="Belmont">Belmont</option>
		<option value="Bethune Cookman">Bethune Cookman</option>
		<option value="Binghamton">Binghamton</option>
		<option value="Boise St.">Boise St.</option>
		<option value="Boston College">Boston College</option>
		<option value="Boston University">Boston University</option>
		<option value="Bowling Green">Bowling Green</option>
		<option value="Bradley">Bradley</option>
		<option value="Brown">Brown</option>
		<option value="Bryant">Bryant</option>
		<option value="Bucknell">Bucknell</option>
		<option value="Buffalo">Buffalo</option>
		<option value="Butler">Butler</option>
		<option value="Cal Baptist">Cal Baptist</option>
		<option value="Cal Poly">Cal Poly</option>
		<option value="Cal St. Bakersfield">Cal St. Bakersfield</option>
		<option value="Cal St. Fullerton">Cal St. Fullerton</option>
		<option value="Cal St. Northridge">Cal St. Northridge</option>
		<option value="California">California</option>
		<option value="Campbell">Campbell</option>
		<option value="Canisius">Central Arkansas</option>
		<option value="Central Connecticut">Central Connecticut</option>
		<option value="Central Michigan">Central Michigan</option>
		<option value="Charleston">Charleston</option>
		<option value="Charleston Southern">Charleston Southern</option>
		<option value="Charlotte">Charlotte</option>
		<option value="Chattanooga">Chattanooga</option>
		<option value="Chicago St.">Chicago St.</option>
		<option value="Cincinnati">Cincinnati</option>
		<option value="Clemson">Clemson</option>
		<option value="Cleveland St.">Cleveland St.</option>
		<option value="Coastal Carolina">Coastal Carolina</option>
		<option value="Colgate">Colgate</option>
		<option value="Colorado">Colorado</option>
		<option value="Colorado St.">Colorado St.</option>
		<option value="Columbia">Columbia</option>
		<option value="Connecticut">Connecticut</option>
		<option value="Coppin St.">Coppin St.</option>
		<option value="Cornell">Cornell</option>
		<option value="Creighton">Creighton</option>
		<option value="Dartmouth">Dartmouth</option>
		<option value="Davidson">Davidson</option>
		<option value="Dayton">Dayton</option>
		<option value="DePaul">DePaul</option>
		<option value="Delaware">Delaware</option>
		<option value="Delaware St.">Delaware St.</option>
		<option value="Denver">Denver</option>
		<option value="Detroit">Detroit</option>
		<option value="Drake">Drake</option>
		<option value="Drexel">Drexel</option>
		<option value="Duke">Duke</option>
		<option value="Duquesne">Duquesne</option>
		<option value="East Carolina">East Carolina</option>
		<option value="East Tennessee St.">East Tennessee St.</option>
		<option value="Eastern Illinois">Eastern Illinois</option>
		<option value="Eastern Kentucky">Eastern Kentucky</option>
		<option value="Eastern Michigan">Eastern Michigan</option>
		<option value="Eastern Washington">Eastern Washington</option>
		<option value="Elon">Elon</option>
		<option value="Evansville">Evansville</option>
		<option value="FIU">FIU</option>
		<option value="Fairfield">Fairfield</option>
		<option value="Fairleigh Dickinson">Fairleigh Dickinson</option>
		<option value="Florida">Florida</option>
		<option value="Florida A&M">Florida A&M</option>
		<option value="Florida Atlantic">Florida Atlantic</option>
		<option value="Florida Gulf Coast">Florida Gulf Coast</option>
		<option value="Florida St.">Florida St.</option>
		<option value="Fresno St.">Fresno St.</option>
		<option value="Furman">Furman</option>
		<option value="Gardner Webb">Gardner Webb</option>
		<option value="George Mason">George Mason</option>
		<option value="George Washington">George Washington</option>
		<option value="Georgetown">Georgetown</option>
		<option value="Georgia">Georgia</option>
		<option value="Georgia Southern">Georgia Southern</option>
		<option value="Georgia St.">Georgia St.</option>
		<option value="Georgia Tech">Georgia Tech</option>
		<option value="Gonzaga">Gonzaga</option>
		<option value="Grambling St.">Grambling St.</option>
		<option value="Grand Canyon">Grand Canyon</option>
		<option value="Green Bay">Green Bay</option>
		<option value="Hampton">Hampton</option>
		<option value="Hartford">Hartford</option>
		<option value="Harvard">Harvard</option>
		<option value="Hawaii">Hawaii</option>
		<option value="High Point">High Point</option>
		<option value="Hofstra">Hofstra</option>
		<option value="Holy Cross">Holy Cross</option>
		<option value="Houston">Houston</option>
		<option value="Houston Baptist">Houston Baptist</option>
		<option value="Howard">Howard</option>
		<option value="IUPUI">IUPUI</option>
		<option value="Idaho">Idaho</option>
		<option value="Idaho St.">Idaho St.</option>
		<option value="Illinois">Illinois</option>
		<option value="Illinois Chicago">Illinois Chicago</option>
		<option value="Illinois St.">Illinois St.</option>
		<option value="Incarnate Word">Incarnate Word</option>
		<option value="Indiana">Indiana</option>
		<option value="Indiana St.">Indiana St.</option>
		<option value="Iona">Iona</option>
		<option value="Iowa">Iowa</option>
		<option value="Iowa St.">Iowa St.</option>
		<option value="Jackson St.">Jackson St.</option>
		<option value="Jacksonville">Jacksonville</option>
		<option value="Jacksonville St.">Jacksonville St.</option>
		<option value="James Madison">James Madison</option>
		<option value="Kansas">Kansas</option>
		<option value="Kansas St.">Kansas St.</option>
		<option value="Kennesaw St.">Kennesaw St.</option>
		<option value="Kent St.">Kent St.</option>
		<option value="Kentucky">Kentucky</option>
		<option value="LIU">LIU</option>
		<option value="LSU">LSU</option>
		<option value="La Salle">La Salle</option>
		<option value="Lafayette">Lafayette</option>
		<option value="Lamar">Lamar</option>
		<option value="Lehigh">Lehigh</option>
		<option value="Liberty">Liberty</option>
		<option value="Lipscomb">Lipscomb</option>
		<option value="Little Rock">Little Rock</option>
		<option value="Long Beach St.">Long Beach St.</option>
		<option value="Longwood">Longwood</option>
		<option value="Louisiana">Louisiana</option>
		<option value="Louisiana Monroe">Louisiana Monroe</option>
		<option value="Louisiana Tech">Louisiana Tech</option>
		<option value="Louisville">Louisville</option>
		<option value="Loyola Chicago">Loyola Chicago</option>
		<option value="Loyola MD">Loyola MD</option>
		<option value="Loyola Marymount">Loyola Marymount</option>
		<option value="Maine">Maine</option>
		<option value="Manhattan">Manhattan</option>
		<option value="Marquette">Marquette</option>
		<option value="Marshall">Marshall</option>
		<option value="Maryland">Maryland</option>
		<option value="Maryland Eastern Shore">Maryland Eastern Shore</option>
		<option value="Massachusetts">Massachusetts</option>
		<option value="McNeese St.">McNeese St.</option>
		<option value="Memphis">Memphis</option>
		<option value="Mercer">Mercer</option>
		<option value="Merrimack">Merrimack</option>
		<option value="Miami FL">Miami FL</option>
		<option value="Miami OH">Miami OH</option>
		<option value="Michigan">Michigan</option>
		<option value="Michigan St.">Michigan St.</option>
		<option value="Middle Tennessee">Middle Tennessee</option>
		<option value="Milwaukee">Milwaukee</option>
		<option value="Minnesota">Minnesota</option>
		<option value="Mississippi">Mississippi</option>
		<option value="Mississippi St.">Mississippi St.</option>
		<option value="Mississippi Valley St.">Mississippi Valley St.</option>
		<option value="Missouri">Missouri</option>
		<option value="Missouri St.">Missouri St.</option>
		<option value="Monmouth">Monmouth</option>
		<option value="Montana">Montana</option>
		<option value="Montana St.">Montana St.</option>
		<option value="Morehead St.">Morehead St.</option>
		<option value="Morgan St.">Morgan St.</option>
		<option value="Mount St. Marys">Mount St. Marys</option>
		<option value="Murray St.">Murray St.</option>
		<option value="N.C. State">N.C. State</option>
		<option value="NJIT">NJIT</option>
		<option value="Navy">Navy</option>
		<option value="Nebraska">Nebraska</option>
		<option value="Nebraska Omaha">Nebraska Omaha</option>
		<option value="Nevada">Nevada</option>
		<option value="New Hampshire">New Hampshire</option>
		<option value="New Mexico">New Mexico</option>
		<option value="New Mexico St.">New Mexico St.</option>
		<option value="New Orleans">New Orleans</option>
		<option value="Niagara">Niagara</option>
		<option value="Nicholls St.">Nicholls St.</option>
		<option value="Norfolk St.">Norfolk St.</option>
		<option value="North Alabama">North Alabama</option>
		<option value="North Carolina">North Carolina</option>
		<option value="North Carolina A&T">North Carolina A&T</option>
		<option value="North Carolina Central">North Carolina Central</option>
		<option value="North Dakota">North Dakota</option>
		<option value="North Dakota St.">North Dakota St.</option>
		<option value="North Florida">North Florida</option>
		<option value="North Dakota St.">North Dakota St.</option>
		<option value="North Florida">North Florida</option>
		<option value="North Texas">North Texas</option>
		<option value="Northeastern">Northeastern</option>
		<option value="Northern Arizona">Northern Arizona</option>
		<option value="Northern Colorado">Northern Colorado</option>
		<option value="Northern Illinois">Northern Illinois</option>
		<option value="Northern Iowa">Northern Iowa</option>
		<option value="Northern Kentucky">Northern Kentucky</option>
		<option value="Northwestern">Northwestern</option>
		<option value="Northwestern St.">Northwestern St.</option>
		<option value="Notre Dame">Notre Dame</option>
		<option value="Oakland">Oakland</option>
		<option value="Ohio">Ohio</option>
		<option value="Ohio St.">Ohio St.</option>
		<option value="Oklahoma">Oklahoma</option>
		<option value="Oklahoma St.">Oklahoma St.</option>
		<option value="Old Dominion">Old Dominion</option>
		<option value="Oral Roberts">Oral Roberts</option>
		<option value="Oregon">Oregon</option>
		<option value="Oregon St.">Oregon St.</option>
		<option value="Pacific">Pacific</option>
		<option value="Penn">Penn</option>
		<option value="Penn St.">Penn St.</option>
		<option value="Pepperdine">Pepperdine</option>
		<option value="Pittsburgh">Pittsburgh</option>
		<option value="Portland">Portland</option>
		<option value="Portland St.">Portland St.</option>
		<option value="Prairie View A&M">Prairie View A&M</option>
		<option value="Presbyterian">Presbyterian</option>
		<option value="Providence">Providence</option>
		<option value="Purdue">Purdue</option>
		<option value="Purdue Fort Wayne">Purdue Fort Wayne</option>
		<option value="Quinnipiac">Quinnipiac</option>
		<option value="Radford">Radford</option>
		<option value="Rhode Island">Rhode Island</option>
		<option value="Rice">Rice</option>
		<option value="Richmond">Richmond</option>
		<option value="Rider">Rider</option>
		<option value="Robert Morris">Robert Morris</option>
		<option value="Rutgers">Rutgers</option>
		<option value="SIU Edwardsville">SIU Edwardsville</option>
		<option value="SMU">SMU</option>
		<option value="Sacramento St.">Sacramento St.</option>
		<option value="Sacred Heart">Sacred Heart</option>
		<option value="Saint Josephs">Saint Joseph's</option>
		<option value="Saint Louis">Saint Louis</option>
		<option value="Saint Marys">Saint Marys</option>
		<option value="Saint Peters">Saint Peter's</option>
		<option value="Sam Houston St.">Sam Houston St.</option>
		<option value="Samford">Samford</option>
		<option value="San Diego">San Diego</option>
		<option value="San Diego St.">San Diego St.</option>
		<option value="San Francisco">San Francisco</option>
		<option value="San Jose St.">San Jose St.</option>
		<option value="Santa Clara">Santa Clara</option>
		<option value="Seattle">Seattle</option>
		<option value="Seton Hall">Seton Hall</option>
		<option value="Siena">Siena</option>
		<option value="South Alabama">South Alabama</option>
		<option value="South Carolina">South Carolina</option>
		<option value="South Carolina St.">South Carolina St.</option>
		<option value="South Dakota">South Dakota</option>
		<option value="South Dakota St.">South Dakota St.</option>
		<option value="South Florida">South Florida</option>
		<option value="Southeast Missouri St.">Southeast Missouri St.</option>
		<option value="Southeastern Louisiana">Southeastern Louisiana</option>
		<option value="Southern">Southern</option>
		<option value="Southern Illinois">Southern Illinois</option>
		<option value="Southern Miss">Southern Miss</option>
		<option value="Southern Utah">Southern Utah</option>
		<option value="St. Bonaventure">St. Bonaventure</option>
		<option value="St. Francis NY">St. Francis NY</option>
		<option value="St. Francis PA">St. Francis PA</option>
		<option value="St. Johns">St. Johns</option>
		<option value="Stanford">Stanford</option>
		<option value="Stephen F. Austin">Stephen F. Austin</option>
		<option value="Stetson">Stetson</option>
		<option value="Stony Brook">Stony Brook</option>
		<option value="Syracuse">Syracuse</option>
		<option value="TCU">TCU</option>
		<option value="Temple">Temple</option>
		<option value="Tennessee">Tennessee</option>
		<option value="Tennessee Martin">Tennessee Martin</option>
		<option value="Tennessee St.">Tennessee St.</option>
		<option value="Tennessee Tech">Tennessee Tech</option>
		<option value="Texas">Texas</option>
		<option value="Texas A&M">Texas A&M</option>
		<option value="Texas A&M Corpus Chris">Texas A&M Corpus Chris</option>
		<option value="Texas Southern">Texas Southern</option>
		<option value="Texas St.">Texas St.</option>
		<option value="Texas Tech">Texas Tech</option>
		<option value="The Citadel">The Citadel</option>
		<option value="Toledo">Toledo</option>
		<option value="Towson">Towson</option>
		<option value="Troy">Troy</option>
		<option value="Tulane">Tulane</option>
		<option value="Tulsa">Tulsa</option>
		<option value="UAB">UAB</option>
		<option value="UC Davis">UC Davis</option>
		<option value="UC Irvine">UC Irvine</option>
		<option value="UC Riverside">UC Riverside</option>
		<option value="UC Santa Barbara">UC Santa Barbara</option>
		<option value="UCF">UCF</option>
		<option value="UCLA">UCLA</option>
		<option value="UMBC">UMBC</option>
		<option value="UMKC">UMKC</option>
		<option value="UMass Lowell">UMass Lowell</option>
		<option value="UNC Asheville">UNC Asheville</option>
		<option value="UNC Greensboro">UNC Greensboro</option>
		<option value="UNC Wilmington">UNC Wilmington</option>
		<option value="UNLV">UNLV</option>
		<option value="USC">USC</option>
		<option value="USC Upstate">USC Upstate</option>
		<option value="UT Arlington">UT Arlington</option>
		<option value="UT Rio Grande Valley">UT Rio Grande Valley</option>
		<option value="UTEP">UTEP</option>
		<option value="UTSA">UTSA</option>
		<option value="Utah">Utah</option>
		<option value="Utah St.">Utah St.</option>
		<option value="Utah Valley">Utah Valley</option>
		<option value="VCU">VCU</option>
		<option value="VMI">VMI</option>
		<option value="Valparaiso">Valparaiso</option>
		<option value="Vanderbilt">Vanderbilt</option>
		<option value="Vermont">Vermont</option>
		<option value="Villanova">Villanova</option>
		<option value="Virginia">Virginia</option>
		<option value="Virginia Tech">Virginia Tech</option>
		<option value="Wagner">Wagner</option>
		<option value="Wake Forest">Wake Forest</option>
		<option value="Washington">Washington</option>
		<option value="Washington St.">Washington St.</option>
		<option value="Weber St.">Weber St.</option>
		<option value="West Virginia">West Virginia</option>
		<option value="Western Carolina">Western Carolina</option>
		<option value="Western Illinois">Western Illinois</option>
		<option value="Western Kentucky">Western Kentucky</option>
		<option value="Western Michigan">Western Michigan</option>
		<option value="Wichita St.">Wichita St.</option>
		<option value="William & Mary">William & Mary</option>
		<option value="Winthrop">Winthrop</option>
		<option value="Wisconsin">Wisconsin</option>
		<option value="Wofford">Wofford</option>
		<option value="Wright St.">Wright St.</option>
		<option value="Wyoming">Wyoming</option>
		<option value="Xavier">Xavier</option>
		<option value="Yale">Yale</option>
		<option value="Youngstown St.">Youngstown St.</option>	
	</select> <br>
	
	Choose an away team:
	<select id="homeTeam" name="awayTeam">
		<option value="Abilene Christian">Abilene Christian</option>
		<option value="Air Force">Air Force</option>
		<option value="Akron">Akron</option>
		<option value="Alabama">Alabama</option>
		<option value="Alabama A&M">Alabama A&M</option>
		<option value="Alabama St.">Alabama St.</option>
		<option value="Albany">Albany</option>
		<option value="Alcorn St.">Alcorn St.</option>
		<option value="American">American</option>
		<option value="Appalachian St.">Appalachian St.</option>
		<option value="Arizona">Arizona</option>
		<option value="Arizona St.">Arizona St.</option>
		<option value="Arkansas">Arkansas</option>
		<option value="Arkansas Pine Bluff">Arkansas Pine Bluff</option>
		<option value="Arkansas St.">Arkansas St.</option>
		<option value="Army">Army</option>
		<option value="Auburn">Auburn</option>
		<option value="Austin Peay">Austin Peay</option>
		<option value="BYU">BYU</option>
		<option value="Ball St.">Ball St.</option>
		<option value="Baylor">Baylor</option>
		<option value="Belmont">Belmont</option>
		<option value="Bethune Cookman">Bethune Cookman</option>
		<option value="Binghamton">Binghamton</option>
		<option value="Boise St.">Boise St.</option>
		<option value="Boston College">Boston College</option>
		<option value="Boston University">Boston University</option>
		<option value="Bowling Green">Bowling Green</option>
		<option value="Bradley">Bradley</option>
		<option value="Brown">Brown</option>
		<option value="Bryant">Bryant</option>
		<option value="Bucknell">Bucknell</option>
		<option value="Buffalo">Buffalo</option>
		<option value="Butler">Butler</option>
		<option value="Cal Baptist">Cal Baptist</option>
		<option value="Cal Poly">Cal Poly</option>
		<option value="Cal St. Bakersfield">Cal St. Bakersfield</option>
		<option value="Cal St. Fullerton">Cal St. Fullerton</option>
		<option value="Cal St. Northridge">Cal St. Northridge</option>
		<option value="California">California</option>
		<option value="Campbell">Campbell</option>
		<option value="Canisius">Central Arkansas</option>
		<option value="Central Connecticut">Central Connecticut</option>
		<option value="Central Michigan">Central Michigan</option>
		<option value="Charleston">Charleston</option>
		<option value="Charleston Southern">Charleston Southern</option>
		<option value="Charlotte">Charlotte</option>
		<option value="Chattanooga">Chattanooga</option>
		<option value="Chicago St.">Chicago St.</option>
		<option value="Cincinnati">Cincinnati</option>
		<option value="Clemson">Clemson</option>
		<option value="Cleveland St.">Cleveland St.</option>
		<option value="Coastal Carolina">Coastal Carolina</option>
		<option value="Colgate">Colgate</option>
		<option value="Colorado">Colorado</option>
		<option value="Colorado St.">Colorado St.</option>
		<option value="Columbia">Columbia</option>
		<option value="Connecticut">Connecticut</option>
		<option value="Coppin St.">Coppin St.</option>
		<option value="Cornell">Cornell</option>
		<option value="Creighton">Creighton</option>
		<option value="Dartmouth">Dartmouth</option>
		<option value="Davidson">Davidson</option>
		<option value="Dayton">Dayton</option>
		<option value="DePaul">DePaul</option>
		<option value="Delaware">Delaware</option>
		<option value="Delaware St.">Delaware St.</option>
		<option value="Denver">Denver</option>
		<option value="Detroit">Detroit</option>
		<option value="Drake">Drake</option>
		<option value="Drexel">Drexel</option>
		<option value="Duke">Duke</option>
		<option value="Duquesne">Duquesne</option>
		<option value="East Carolina">East Carolina</option>
		<option value="East Tennessee St.">East Tennessee St.</option>
		<option value="Eastern Illinois">Eastern Illinois</option>
		<option value="Eastern Kentucky">Eastern Kentucky</option>
		<option value="Eastern Michigan">Eastern Michigan</option>
		<option value="Eastern Washington">Eastern Washington</option>
		<option value="Elon">Elon</option>
		<option value="Evansville">Evansville</option>
		<option value="FIU">FIU</option>
		<option value="Fairfield">Fairfield</option>
		<option value="Fairleigh Dickinson">Fairleigh Dickinson</option>
		<option value="Florida">Florida</option>
		<option value="Florida A&M">Florida A&M</option>
		<option value="Florida Atlantic">Florida Atlantic</option>
		<option value="Florida Gulf Coast">Florida Gulf Coast</option>
		<option value="Florida St.">Florida St.</option>
		<option value="Fresno St.">Fresno St.</option>
		<option value="Furman">Furman</option>
		<option value="Gardner Webb">Gardner Webb</option>
		<option value="George Mason">George Mason</option>
		<option value="George Washington">George Washington</option>
		<option value="Georgetown">Georgetown</option>
		<option value="Georgia">Georgia</option>
		<option value="Georgia Southern">Georgia Southern</option>
		<option value="Georgia St.">Georgia St.</option>
		<option value="Georgia Tech">Georgia Tech</option>
		<option value="Gonzaga">Gonzaga</option>
		<option value="Grambling St.">Grambling St.</option>
		<option value="Grand Canyon">Grand Canyon</option>
		<option value="Green Bay">Green Bay</option>
		<option value="Hampton">Hampton</option>
		<option value="Hartford">Hartford</option>
		<option value="Harvard">Harvard</option>
		<option value="Hawaii">Hawaii</option>
		<option value="High Point">High Point</option>
		<option value="Hofstra">Hofstra</option>
		<option value="Holy Cross">Holy Cross</option>
		<option value="Houston">Houston</option>
		<option value="Houston Baptist">Houston Baptist</option>
		<option value="Howard">Howard</option>
		<option value="IUPUI">IUPUI</option>
		<option value="Idaho">Idaho</option>
		<option value="Idaho St.">Idaho St.</option>
		<option value="Illinois">Illinois</option>
		<option value="Illinois Chicago">Illinois Chicago</option>
		<option value="Illinois St.">Illinois St.</option>
		<option value="Incarnate Word">Incarnate Word</option>
		<option value="Indiana">Indiana</option>
		<option value="Indiana St.">Indiana St.</option>
		<option value="Iona">Iona</option>
		<option value="Iowa">Iowa</option>
		<option value="Iowa St.">Iowa St.</option>
		<option value="Jackson St.">Jackson St.</option>
		<option value="Jacksonville">Jacksonville</option>
		<option value="Jacksonville St.">Jacksonville St.</option>
		<option value="James Madison">James Madison</option>
		<option value="Kansas">Kansas</option>
		<option value="Kansas St.">Kansas St.</option>
		<option value="Kennesaw St.">Kennesaw St.</option>
		<option value="Kent St.">Kent St.</option>
		<option value="Kentucky">Kentucky</option>
		<option value="LIU">LIU</option>
		<option value="LSU">LSU</option>
		<option value="La Salle">La Salle</option>
		<option value="Lafayette">Lafayette</option>
		<option value="Lamar">Lamar</option>
		<option value="Lehigh">Lehigh</option>
		<option value="Liberty">Liberty</option>
		<option value="Lipscomb">Lipscomb</option>
		<option value="Little Rock">Little Rock</option>
		<option value="Long Beach St.">Long Beach St.</option>
		<option value="Longwood">Longwood</option>
		<option value="Louisiana">Louisiana</option>
		<option value="Louisiana Monroe">Louisiana Monroe</option>
		<option value="Louisiana Tech">Louisiana Tech</option>
		<option value="Louisville">Louisville</option>
		<option value="Loyola Chicago">Loyola Chicago</option>
		<option value="Loyola MD">Loyola MD</option>
		<option value="Loyola Marymount">Loyola Marymount</option>
		<option value="Maine">Maine</option>
		<option value="Manhattan">Manhattan</option>
		<option value="Marquette">Marquette</option>
		<option value="Marshall">Marshall</option>
		<option value="Maryland">Maryland</option>
		<option value="Maryland Eastern Shore">Maryland Eastern Shore</option>
		<option value="Massachusetts">Massachusetts</option>
		<option value="McNeese St.">McNeese St.</option>
		<option value="Memphis">Memphis</option>
		<option value="Mercer">Mercer</option>
		<option value="Merrimack">Merrimack</option>
		<option value="Miami FL">Miami FL</option>
		<option value="Miami OH">Miami OH</option>
		<option value="Michigan">Michigan</option>
		<option value="Michigan St.">Michigan St.</option>
		<option value="Middle Tennessee">Middle Tennessee</option>
		<option value="Milwaukee">Milwaukee</option>
		<option value="Minnesota">Minnesota</option>
		<option value="Mississippi">Mississippi</option>
		<option value="Mississippi St.">Mississippi St.</option>
		<option value="Mississippi Valley St.">Mississippi Valley St.</option>
		<option value="Missouri">Missouri</option>
		<option value="Missouri St.">Missouri St.</option>
		<option value="Monmouth">Monmouth</option>
		<option value="Montana">Montana</option>
		<option value="Montana St.">Montana St.</option>
		<option value="Morehead St.">Morehead St.</option>
		<option value="Morgan St.">Morgan St.</option>
		<option value="Mount St. Mary's">Mount St. Mary's</option>
		<option value="Murray St.">Murray St.</option>
		<option value="N.C. State">N.C. State</option>
		<option value="NJIT">NJIT</option>
		<option value="Navy">Navy</option>
		<option value="Nebraska">Nebraska</option>
		<option value="Nebraska Omaha">Nebraska Omaha</option>
		<option value="Nevada">Nevada</option>
		<option value="New Hampshire">New Hampshire</option>
		<option value="New Mexico">New Mexico</option>
		<option value="New Mexico St.">New Mexico St.</option>
		<option value="New Orleans">New Orleans</option>
		<option value="Niagara">Niagara</option>
		<option value="Nicholls St.">Nicholls St.</option>
		<option value="Norfolk St.">Norfolk St.</option>
		<option value="North Alabama">North Alabama</option>
		<option value="North Carolina">North Carolina</option>
		<option value="North Carolina A&T">North Carolina A&T</option>
		<option value="North Carolina Central">North Carolina Central</option>
		<option value="North Dakota">North Dakota</option>
		<option value="North Dakota St.">North Dakota St.</option>
		<option value="North Florida">North Florida</option>
		<option value="North Dakota St.">North Dakota St.</option>
		<option value="North Florida">North Florida</option>
		<option value="North Texas">North Texas</option>
		<option value="Northeastern">Northeastern</option>
		<option value="Northern Arizona">Northern Arizona</option>
		<option value="Northern Colorado">Northern Colorado</option>
		<option value="Northern Illinois">Northern Illinois</option>
		<option value="Northern Iowa">Northern Iowa</option>
		<option value="Northern Kentucky">Northern Kentucky</option>
		<option value="Northwestern">Northwestern</option>
		<option value="Northwestern St.">Northwestern St.</option>
		<option value="Notre Dame">Notre Dame</option>
		<option value="Oakland">Oakland</option>
		<option value="Ohio">Ohio</option>
		<option value="Ohio St.">Ohio St.</option>
		<option value="Oklahoma">Oklahoma</option>
		<option value="Oklahoma St.">Oklahoma St.</option>
		<option value="Old Dominion">Old Dominion</option>
		<option value="Oral Roberts">Oral Roberts</option>
		<option value="Oregon">Oregon</option>
		<option value="Oregon St.">Oregon St.</option>
		<option value="Pacific">Pacific</option>
		<option value="Penn">Penn</option>
		<option value="Penn St.">Penn St.</option>
		<option value="Pepperdine">Pepperdine</option>
		<option value="Pittsburgh">Pittsburgh</option>
		<option value="Portland">Portland</option>
		<option value="Portland St.">Portland St.</option>
		<option value="Prairie View A&M">Prairie View A&M</option>
		<option value="Presbyterian">Presbyterian</option>
		<option value="Providence">Providence</option>
		<option value="Purdue">Purdue</option>
		<option value="Purdue Fort Wayne">Purdue Fort Wayne</option>
		<option value="Quinnipiac">Quinnipiac</option>
		<option value="Radford">Radford</option>
		<option value="Rhode Island">Rhode Island</option>
		<option value="Rice">Rice</option>
		<option value="Richmond">Richmond</option>
		<option value="Rider">Rider</option>
		<option value="Robert Morris">Robert Morris</option>
		<option value="Rutgers">Rutgers</option>
		<option value="SIU Edwardsville">SIU Edwardsville</option>
		<option value="SMU">SMU</option>
		<option value="Sacramento St.">Sacramento St.</option>
		<option value="Sacred Heart">Sacred Heart</option>
		<option value="Saint Joseph's">Saint Joseph's</option>
		<option value="Saint Louis">Saint Louis</option>
		<option value="Saint Mary's">Saint Mary's</option>
		<option value="Saint Peter's">Saint Peter's</option>
		<option value="Sam Houston St.">Sam Houston St.</option>
		<option value="Samford">Samford</option>
		<option value="San Diego">San Diego</option>
		<option value="San Diego St.">San Diego St.</option>
		<option value="San Francisco">San Francisco</option>
		<option value="San Jose St.">San Jose St.</option>
		<option value="Santa Clara">Santa Clara</option>
		<option value="Seattle">Seattle</option>
		<option value="Seton Hall">Seton Hall</option>
		<option value="Siena">Siena</option>
		<option value="South Alabama">South Alabama</option>
		<option value="South Carolina">South Carolina</option>
		<option value="South Carolina St.">South Carolina St.</option>
		<option value="South Dakota">South Dakota</option>
		<option value="South Dakota St.">South Dakota St.</option>
		<option value="South Florida">South Florida</option>
		<option value="Southeast Missouri St.">Southeast Missouri St.</option>
		<option value="Southeastern Louisiana">Southeastern Louisiana</option>
		<option value="Southern">Southern</option>
		<option value="Southern Illinois">Southern Illinois</option>
		<option value="Southern Miss">Southern Miss</option>
		<option value="Southern Utah">Southern Utah</option>
		<option value="St. Bonaventure">St. Bonaventure</option>
		<option value="St. Francis NY">St. Francis NY</option>
		<option value="St. Francis PA">St. Francis PA</option>
		<option value="St. John's">St. John's</option>
		<option value="Stanford">Stanford</option>
		<option value="Stephen F. Austin">Stephen F. Austin</option>
		<option value="Stetson">Stetson</option>
		<option value="Stony Brook">Stony Brook</option>
		<option value="Syracuse">Syracuse</option>
		<option value="TCU">TCU</option>
		<option value="Temple">Temple</option>
		<option value="Tennessee">Tennessee</option>
		<option value="Tennessee Martin">Tennessee Martin</option>
		<option value="Tennessee St.">Tennessee St.</option>
		<option value="Tennessee Tech">Tennessee Tech</option>
		<option value="Texas">Texas</option>
		<option value="Texas A&M">Texas A&M</option>
		<option value="Texas A&M Corpus Chris">Texas A&M Corpus Chris</option>
		<option value="Texas Southern">Texas Southern</option>
		<option value="Texas St.">Texas St.</option>
		<option value="Texas Tech">Texas Tech</option>
		<option value="The Citadel">The Citadel</option>
		<option value="Toledo">Toledo</option>
		<option value="Towson">Towson</option>
		<option value="Troy">Troy</option>
		<option value="Tulane">Tulane</option>
		<option value="Tulsa">Tulsa</option>
		<option value="UAB">UAB</option>
		<option value="UC Davis">UC Davis</option>
		<option value="UC Irvine">UC Irvine</option>
		<option value="UC Riverside">UC Riverside</option>
		<option value="UC Santa Barbara">UC Santa Barbara</option>
		<option value="UCF">UCF</option>
		<option value="UCLA">UCLA</option>
		<option value="UMBC">UMBC</option>
		<option value="UMKC">UMKC</option>
		<option value="UMass Lowell">UMass Lowell</option>
		<option value="UNC Asheville">UNC Asheville</option>
		<option value="UNC Greensboro">UNC Greensboro</option>
		<option value="UNC Wilmington">UNC Wilmington</option>
		<option value="UNLV">UNLV</option>
		<option value="USC">USC</option>
		<option value="USC Upstate">USC Upstate</option>
		<option value="UT Arlington">UT Arlington</option>
		<option value="UT Rio Grande Valley">UT Rio Grande Valley</option>
		<option value="UTEP">UTEP</option>
		<option value="UTSA">UTSA</option>
		<option value="Utah">Utah</option>
		<option value="Utah St.">Utah St.</option>
		<option value="Utah Valley">Utah Valley</option>
		<option value="VCU">VCU</option>
		<option value="VMI">VMI</option>
		<option value="Valparaiso">Valparaiso</option>
		<option value="Vanderbilt">Vanderbilt</option>
		<option value="Vermont">Vermont</option>
		<option value="Villanova">Villanova</option>
		<option value="Virginia">Virginia</option>
		<option value="Virginia Tech">Virginia Tech</option>
		<option value="Wagner">Wagner</option>
		<option value="Wake Forest">Wake Forest</option>
		<option value="Washington">Washington</option>
		<option value="Washington St.">Washington St.</option>
		<option value="Weber St.">Weber St.</option>
		<option value="West Virginia">West Virginia</option>
		<option value="Western Carolina">Western Carolina</option>
		<option value="Western Illinois">Western Illinois</option>
		<option value="Western Kentucky">Western Kentucky</option>
		<option value="Western Michigan">Western Michigan</option>
		<option value="Wichita St.">Wichita St.</option>
		<option value="William & Mary">William & Mary</option>
		<option value="Winthrop">Winthrop</option>
		<option value="Wisconsin">Wisconsin</option>
		<option value="Wofford">Wofford</option>
		<option value="Wright St.">Wright St.</option>
		<option value="Wyoming">Wyoming</option>
		<option value="Xavier">Xavier</option>
		<option value="Yale">Yale</option>
		<option value="Youngstown St.">Youngstown St.</option>
	</select> <br>
	<input type="submit" value="Analyze">
	<br>
	</form>
	
</body>
</html>